AWSTemplateFormatVersion: '2010-09-09'
Description: Eranova Technical - Lambda Function

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: eranova-technical
      Runtime: python3.12
      Handler: handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code: src/
      Timeout: 30
      MemorySize: 128

Outputs:
  LambdaFunctionName:
    Value: !Ref LambdaFunction
  LambdaFunctionArn:
    Value: !GetAtt LambdaFunction.Arn
